-- =============================================================
-- CAMPUSDESK · Estructura de la base de datos
-- Dueño: Persona 4
--
-- Preparación (una sola vez, en psql o pgAdmin):
--   CREATE DATABASE campusdesk;
-- Luego ejecutar este archivo conectado a la base campusdesk.
--
-- Tablas: users, tickets, comments, status_history
-- Incluir: claves foráneas, UNIQUE, NOT NULL y CHECK de los enums.
-- =============================================================

-- Borra todo para poder recrear la base desde cero (orden inverso por las claves foráneas).
DROP TABLE IF EXISTS status_history;
DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS tickets;
DROP TABLE IF EXISTS users;

-- Las columnas deben coincidir con las entidades JPA (paquete entity) para usar ddl-auto: validate.

CREATE TABLE users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name   VARCHAR(100) NOT NULL,
    email       VARCHAR(150) NOT NULL,
    password    VARCHAR(255) NOT NULL,
    role        VARCHAR(20)  NOT NULL,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT ck_users_role  CHECK (role IN ('ADMIN', 'TECHNICIAN', 'USER'))
);

CREATE TABLE tickets (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title          VARCHAR(150)  NOT NULL,
    description    VARCHAR(2000) NOT NULL,
    category       VARCHAR(20)   NOT NULL,
    priority       VARCHAR(20)   NOT NULL,
    status         VARCHAR(20)   NOT NULL DEFAULT 'OPEN',
    requester_id   BIGINT        NOT NULL,
    technician_id  BIGINT,
    created_at     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_tickets_requester  FOREIGN KEY (requester_id)  REFERENCES users (id),
    CONSTRAINT fk_tickets_technician FOREIGN KEY (technician_id) REFERENCES users (id),
    CONSTRAINT ck_tickets_category CHECK (category IN ('HARDWARE', 'SOFTWARE', 'NETWORK', 'ACCESS', 'OTHER')),
    CONSTRAINT ck_tickets_priority CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    CONSTRAINT ck_tickets_status   CHECK (status IN ('OPEN', 'ASSIGNED', 'IN_PROGRESS', 'RESOLVED', 'CLOSED'))
);

CREATE TABLE comments (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id   BIGINT        NOT NULL,
    author_id   BIGINT        NOT NULL,
    content     VARCHAR(1000) NOT NULL,
    created_at  TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_comments_ticket FOREIGN KEY (ticket_id) REFERENCES tickets (id) ON DELETE CASCADE,
    CONSTRAINT fk_comments_author FOREIGN KEY (author_id) REFERENCES users (id)
);

CREATE TABLE status_history (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id        BIGINT      NOT NULL,
    previous_status  VARCHAR(20),
    new_status       VARCHAR(20) NOT NULL,
    changed_by_id    BIGINT      NOT NULL,
    changed_at       TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_status_history_ticket     FOREIGN KEY (ticket_id)     REFERENCES tickets (id) ON DELETE CASCADE,
    CONSTRAINT fk_status_history_changed_by FOREIGN KEY (changed_by_id) REFERENCES users (id),
    CONSTRAINT ck_status_history_previous CHECK (previous_status IN ('OPEN', 'ASSIGNED', 'IN_PROGRESS', 'RESOLVED', 'CLOSED')),
    CONSTRAINT ck_status_history_new      CHECK (new_status      IN ('OPEN', 'ASSIGNED', 'IN_PROGRESS', 'RESOLVED', 'CLOSED'))
);

-- Índices para las consultas frecuentes: listados por rol, comentarios e historial de un ticket.
CREATE INDEX idx_tickets_requester      ON tickets (requester_id);
CREATE INDEX idx_tickets_technician     ON tickets (technician_id);
CREATE INDEX idx_tickets_status         ON tickets (status);
CREATE INDEX idx_comments_ticket        ON comments (ticket_id);
CREATE INDEX idx_status_history_ticket  ON status_history (ticket_id);
